require('dotenv').config();

module.exports = {
  token: process.env.DISCORD_TOKEN,
  clientId: process.env.CLIENT_ID,
  port: Number(process.env.PORT || 3000),
  dashboardToken: process.env.DASHBOARD_TOKEN || 'change_me_to_a_strong_password',
  alertWebhook: process.env.ALERT_WEBHOOK_URL || '',
  dataFile: require('path').join(__dirname, '..', 'data', 'store.json'),
  invitesFile: require('path').join(__dirname, '..', 'data', 'invites.json'),

  defaults: {
    prefix: '?',
    antiSpam: {
      enabled: true,
      maxMessages: 6,
      windowSec: 10,
      action: 'timeout',
      timeoutMinutes: 10,
      maxMentions: 5,
      mentionAction: 'timeout',
    },
    antiRaid: {
      enabled: true,
      maxJoins: 5,
      windowSec: 30,
      lockdownDurationMin: 10,
      autoVerify: true,
    },
    autoMod: {
      enabled: true,
      bannedWords: [],
      filterLinks: true,
      blockAllLinks: true,
      allowedDomains: ['discord.com', 'discord.gg', 'tenor.com', 'giphy.com', 'youtube.com', 'twitter.com', 'x.com', 'github.com', 'twitch.tv'],
      filterInvites: true,
      filterEveryone: true,
      maxCapsPercent: 70,
      minLengthForCaps: 8,
      timeoutMinutes: 5,
    },
    antiNuke: {
      enabled: true,
      maxChannelDeletes: 5,
      maxRoleDeletes: 5,
      maxBans: 5,
      maxKicks: 5,
      maxWebhooks: 3,
      maxBots: 2,
      kickBotsOnJoin: true,
      windowSec: 30,
      lockdownMinutes: 15,
      autoRestore: true,
      autoProtectRoles: true,
      protectedRoles: [],
    },
    audit: {
      enabled: true,
      channelId: '',
      logMessages: true,
      logMembers: true,
      logModActions: true,
      logChannels: true,
      logRoles: true,
    },
    verification: {
      enabled: false,
      roleId: '',
      logChannelId: '',
      buttonLabel: 'Verify Me',
      buttonEmoji: '✅',
      welcomeMessage: '',
    },
    access: {
      mode: 'everyone',
      users: [],
      roles: [],
    },
    welcome: {
      enabled: false,
      channelId: '',
      message: '👋 Welcome {mention} to **{guild}**! We now have **{memberCount}** members. Enjoy your stay!',
    },
    farewell: {
      enabled: false,
      channelId: '',
      message: '👋 **{userTag}** left the server. We now have **{memberCount}** members.',
    },
    autoRole: {
      enabled: false,
      roleId: '',
    },
    autoNick: {
      enabled: false,
      prefix: '',
      suffix: '',
    },
    voice: {
      lang: 'ta',
      sttLang: 'auto',
      sttModel: 'Xenova/whisper-tiny',
    },
    joinLog: {
      enabled: false,
      channelId: '',
    },
    leaveLog: {
      enabled: false,
      channelId: '',
    },
    extraOwners: [],
    roleAuth: {
      enabled: false,
      rules: [],
    },
    quarantine: {
      roleId: '',
      channelId: '',
    },
    tempVoice: {
      enabled: false,
      channelId: '',
      categoryId: '',
      lockOnClaim: false,
    },
    mediaChannels: [],
    autoResponder: {
      enabled: true,
      rules: [],
    },
    customCommands: [],
    tickets: {
      enabled: false,
      panelChannelId: '',
      categoryId: '',
      supportRoleId: '',
    },
    activityRoles: [],
    giveaway: {
      defaultChannelId: '',
    },
    economy: {
      enabled: true,
      daily: 250,
      workMin: 50,
      workMax: 150,
      startBalance: 100,
    },
  },
};
